spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/shopfront
    username: shopfront
    password: shopfront

  sql:
    init:
      mode: always

  data:
    redis:
      host: localhost
      port: 6379

  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID:market-app}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:please-override}
            authorization-grant-type: client_credentials
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8082/realms/market}

cache:
  item:
    ttl-minutes: 5

payment:
  service:
    url: http://localhost:8081
