spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/shopfront
    username: shopfront
    password: shopfront

  sql:
    init:
      mode: always

  data:
    redis:
      host: localhost
      port: 6379

  thymeleaf:
    cache: false

cache:
  item:
    ttl-minutes: 5
