CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    img_path    VARCHAR(255),
    price       BIGINT       NOT NULL
);

CREATE TABLE IF NOT EXISTS cart_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    item_id    BIGINT       NOT NULL REFERENCES items (id),
    count      INT          NOT NULL DEFAULT 1,
    UNIQUE (session_id, item_id)
);

CREATE TABLE IF NOT EXISTS customer_orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    total_sum  BIGINT       NOT NULL,
    created_at TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS order_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT       NOT NULL REFERENCES customer_orders (id),
    item_id  BIGINT,
    title    VARCHAR(255) NOT NULL,
    price    BIGINT       NOT NULL,
    count    INT          NOT NULL
);
