server:
  port: 8081

payment:
  initial-balance: 100000  # 1000 rubles in kopecks

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8082/realms/market}
