-- Test schema for H2 R2DBC.
-- Drops any existing FK constraints before recreating columns, since H2 in-memory
-- DB persists across tests within a single JVM run and FK constraints from earlier
-- runs (where users(id) was referenced) would otherwise block inserts.

DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS customer_orders;
DROP TABLE IF EXISTS cart_items;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS items;

CREATE TABLE items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    img_path    VARCHAR(255),
    price       BIGINT       NOT NULL
);

CREATE TABLE cart_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255),
    user_id    BIGINT,
    item_id    BIGINT       NOT NULL REFERENCES items (id),
    count      INT          NOT NULL DEFAULT 1
);

CREATE TABLE customer_orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255),
    user_id    BIGINT,
    total_sum  BIGINT       NOT NULL,
    created_at TIMESTAMP    NOT NULL
);

CREATE TABLE order_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT       NOT NULL REFERENCES customer_orders (id),
    item_id  BIGINT,
    title    VARCHAR(255) NOT NULL,
    price    BIGINT       NOT NULL,
    count    INT          NOT NULL
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64)  NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    enabled  BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE INDEX ix_cart_items_user_id      ON cart_items(user_id);
CREATE INDEX ix_customer_orders_user_id ON customer_orders(user_id);
