-- Test schema for H2 R2DBC (used by @DataR2dbcTest and @SpringBootTest with test profile).
--
-- H2 version 2.x dropped AUTO_INCREMENT in favour of the SQL standard:
--   BIGINT GENERATED BY DEFAULT AS IDENTITY
-- This is identical to the production PostgreSQL DDL, so both share the same syntax.
-- IF NOT EXISTS guards prevent errors when the shared in-memory DB is reused across tests.

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    img_path    VARCHAR(255),
    price       BIGINT       NOT NULL
    );

CREATE TABLE IF NOT EXISTS cart_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    item_id    BIGINT       NOT NULL REFERENCES items (id),
    count      INT          NOT NULL DEFAULT 1,
    UNIQUE (session_id, item_id)
    );

CREATE TABLE IF NOT EXISTS customer_orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    total_sum  BIGINT       NOT NULL,
    created_at TIMESTAMP    NOT NULL
    );

CREATE TABLE IF NOT EXISTS order_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT       NOT NULL REFERENCES customer_orders (id),
    item_id  BIGINT,
    title    VARCHAR(255) NOT NULL,
    price    BIGINT       NOT NULL,
    count    INT          NOT NULL
    );

CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64)  NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    enabled  BOOLEAN      NOT NULL DEFAULT TRUE
    );

ALTER TABLE cart_items      ADD COLUMN IF NOT EXISTS user_id BIGINT REFERENCES users(id);
ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS user_id BIGINT REFERENCES users(id);

CREATE INDEX IF NOT EXISTS ix_cart_items_user_id      ON cart_items(user_id);
CREATE INDEX IF NOT EXISTS ix_customer_orders_user_id ON customer_orders(user_id);
